/golden-island
    /images
        logo.png
        cover.jpg
    /css
        styles.css
    index.html
    golden-bar.html
    golden-wave.html
    golden-island-venue.html
    golden-stage.html
    golden-beer-club.html
    script.js
