/goldenislandretreat
    cover.jpg
    golden-bar.html
    golden-beer-club.html
    golden-island-venue.html
    golden-stage.html
    golden-wave.html
    index.html
    logo.png
    script.js
    styles.css
